Vue.createApp({
  data() {
    return {
      firstName: '',
      lastName: '',
      street: '',
      city: '',
      state: 'AL',
      states: [
        { value: 'AL', name: 'Alabama' },
        { value: 'AK', name: 'Alaska' },
        { value: 'AZ', name: 'Arizona' },
        { value: 'AR', name: 'Arkansas' },
        { value: 'CA', name: 'California' },
        { value: 'CO', name: 'Colorado' },
        { value: 'CT', name: 'Connecticut' },
        { value: 'DE', name: 'Delaware' },
        { value: 'FL', name: 'Florida' },
        { value: 'GA', name: 'Georgia' },
        { value: 'HI', name: 'Hawaii' },
        { value: 'ID', name: 'Idaho' },
        { value: 'IL', name: 'Illinois' },
        { value: 'IN', name: 'Indiana' },
        { value: 'IA', name: 'Iowa' },
        { value: 'KS', name: 'Kansas' },
        { value: 'KY', name: 'Kentucky' },
        { value: 'LA', name: 'Louisiana' },
        { value: 'ME', name: 'Maine' },
        { value: 'MD', name: 'Maryland' },
        { value: 'MA', name: 'Massachusetts' },
        { value: 'MI', name: 'Michigan' },
        { value: 'MN', name: 'Minnesota' },
        { value: 'MS', name: 'Mississippi' },
        { value: 'MO', name: 'Missouri' },
        { value: 'MT', name: 'Montana' },
        { value: 'NE', name: 'Nebraska' },
        { value: 'NV', name: 'Nevada' },
        { value: 'NH', name: 'New Hampshire' },
        { value: 'NJ', name: 'New Jersey' },
        { value: 'NM', name: 'New Mexico' },
        { value: 'NY', name: 'New York' },
        { value: 'NC', name: 'North Carolina' },
        { value: 'ND', name: 'North Dakota' },
        { value: 'OH', name: 'Ohio' },
        { value: 'OK', name: 'Oklahoma' },
        { value: 'OR', name: 'Oregon' },
        { value: 'PA', name: 'Pennsylvania' },
        { value: 'RI', name: 'Rhode Island' },
        { value: 'SC', name: 'South Carolina' },
        { value: 'SD', name: 'South Dakota' },
        { value: 'TN', name: 'Tennessee' },
        { value: 'TX', name: 'Texas' },
        { value: 'UT', name: 'Utah' },
        { value: 'VT', name: 'Vermont' },
        { value: 'VA', name: 'Virginia' },
        { value: 'WA', name: 'Washington' },
        { value: 'WV', name: 'West Virginia' },
        { value: 'WI', name: 'Wisconsin' },
        { value: 'WY', name: 'Wyoming' }
      ],
      zipcode: '',
      country: '',
      selectedColors: [],
      colors: [
        { name: 'Beige', value: 'beige'},
        { name: 'Black - Bay', value: 'black-bay'},
        { name: 'Black - True', value: 'black-true'},
        { name: 'Brown - Light', value: 'brown-lt'},
        { name: 'Brown - Medium', value: 'brown-md'},
        { name: 'Brown - Dark', value: 'brown-dk'},
        { name: 'Fawn - Light', value: 'fawn-lt'},
        { name: 'Fawn - Medium', value: 'fawn-md'},
        { name: 'Fawn - Dark', value: 'fawn-dk'},
        { name: 'Rose Grey - Light', value: 'rose-grey-lt'},
        { name: 'Rose Grey - Medium', value: 'rose-grey-md'},
        { name: 'Rose Grey - Dark', value: 'rose-grey-dk'},
        { name: 'Silver Grey - Light', value: 'silver-grey-lt'},
        { name: 'Silver Grey - Medium', value: 'silver-grey-md'},
        { name: 'Silver Grey - Dark', value: 'silver-grey-dk'},
        { name: 'White', value: 'white'}
      ],
      status: ''
    }
  }
}).mount('#formApp')